### ISSUE TITLE
Unable to track on server but able to on local machine

### ISSUE THREAD

**Issue by seanjkanderson** [acte-solutions/matomophptracker-plugin#3]
I'm trying to set up Matomo for page view tracking. I have the Matomo URL, site ID, and token set and the tracker enabled in your plugin. However, Matomo only registers any activity (e.g. views) when I test it on my local machine and not when someone hits my website on the server. I have verified that the MatomoTracker.php file is accessible on the server such that 
```
require_once $path;
MatomoTracker::$URL = 'http://matomo.my_domain.com/';
```
can be run without issue.

If it makes a difference, my Matomo installation and my website share a server.

Thanks!

**Comment by AdrienAdB** [comment]
Hello @seanjkanderson, as it works in local machine, it may be a misconfiguration in your server.

From your OctoberCMS server can you access your Matomo instance with curl for example?

```bash
curl http://matomo.my_domain.com/ -I
```

Is there anything in OctoberCMS eventlogs?

**Comment by seanjkanderson** [comment]
Thanks for your reply @AdrienAdB. The curl command returns a 200 and generally
looks okay. I'm running the site in debug mode and it's not throwing any
errors. I verified that the file path is what I expect it to be and that
the server can access it.

**Comment by seanjkanderson** [comment]
@AdrienAdB Is there another test worth doing? I double checked the OctoberCMS logs and there aren't any errors given my current configurations. Not sure if there is something in the JS that should not be there? Thank you

```
<head>
    <!-- Matomo -->
    <script type="text/javascript">
        var _paq = window._paq = window._paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
        var u="//matomo.philandersonphotography.com/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '1']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
        })();
    </script>
    <!-- End Matomo Code -->
  
</head>
```

EDIT: I just found there is a JS error: 
`Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID`. Do you know the meaning of this?

EDIT: only works with HTTPS i guess

**Comment by AdrienAdB** [comment]
This plugin is for server side tracking only. If you use the Javascript client, you don't need this plugin.
You're right, you cannot load http on https website, your browser will block it.

Best Regards.
